config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'puppies#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :puppies, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :edit, :update] do
    member do
      get 'accept', to: 'bookings#accept'
      get 'reject', to: 'bookings#reject'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :puppy
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/puppy.rb
class Puppy < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :puppies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?
  # def configure_permitted_parameters
  #   # For additional fields in app/views/devise/registrations/new.html.erb
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  #   # For additional in app/views/devise/registrations/edit.html.erb
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  # end

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

   private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
    # @bookings = booking.puppy.user
    @owner_puppies = Puppy.where(user_id: current_user.id)
    # @owner_bookings = @owner_puppy.bookings
    @current_user_bookings = Booking.where(user_id: current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @puppy = Puppy.find(params[:puppy_id])
    @booking = Booking.new
    @puppies = Puppy.all
    authorize @booking
  end

  def create
    @puppy = Puppy.find(params[:puppy_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    authorize @booking
    @booking.puppy = @puppy
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def accept

    @booking = Booking.find(params[:id])
    @booking.accepted = true
    @booking.save
    redirect_to bookings_path
    authorize @booking
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.accepted = false
    @booking.save
    redirect_to bookings_path
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :puppy_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index]

  def home
  end
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  before_action :set_puppy, only: [:show, :edit, :update, :destroy]

  def index
    @puppies = policy_scope(Puppy)
    @markers = @puppies.geocoded.map do |puppy|
      {
        lat: puppy.latitude,
        lng: puppy.longitude,
        infoWindow: render_to_string(partial: "shared/info_window", locals: { puppy: puppy })
      }
    end
  end

  def show
    authorize @puppy
  end

  def new
    @puppy = Puppy.new
    authorize @puppy
  end

  def create
    @puppy = Puppy.new(puppy_params)
    @puppy.user = current_user
    authorize @puppy
    if @puppy.save!
      redirect_to puppy_path(@puppy)
    else
      render 'new'
    end
  end

  def edit
    authorize @puppy
  end

  def update
    if @puppy.update(puppy_params)
      redirect_to puppy_path(@puppy)
    else
      render :edit
    end
  end

  def destroy
    @puppy.destroy
    redirect_to root_path
  end

  private

  def set_puppy
    @puppy = Puppy.find(params[:id])
  end

  def puppy_params
    params.require(:puppy).permit(:name, :description, :price, :photo, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
<%# if current_user == @current_user_bookings %>
  <% @owner_puppies.each do |puppy| %>
  <% if puppy.bookings.count > 0 %>
  <h1>Here are <%= puppy.name %> bookings:</h1>
    <div class="card-confirm">

      <% puppy.bookings.each do |booking|  %>
          <div class="card-product my-3">
            <%= cl_image_tag booking.puppy.photo.key %>
            <div class="card-product-infos pb-3">
              <h2><%= link_to booking.puppy.name, puppy_path(booking.puppy) %></h2>
              <p>The session will start on the <%= booking.start_date %> until the <%= booking.end_date %></p>
              <% if booking.accepted == nil  %>
                  <p> Do you want to accept this booking? </p>
                  <%= link_to 'Yes, accept!', accept_booking_path(booking), class: "btn btn-outline-success btn-sm"%>
                  <%= link_to 'No, reject!', reject_booking_path(booking), class: "btn btn-outline-warning btn-sm" %>
                <% elsif booking.accepted == false %>
                  <p>You <strong>rejected</strong> this session!</p>
                <% else %>
                  <p>You <strong>confirmed</strong> this session!</p>
              <% end %>
               </div>
            </div>
     <% end %>
      </div>
    <% end %>
    <% end %>


  <%# else %>
  <h1>See your booked sessions:</h1>
    <div class="card-confirm">
      <div class="container">
      <% @current_user_bookings.each do |booking| %>
        <div class="card-product my-3">
          <%= cl_image_tag booking.puppy.photo.key %>
          <div class="card-product-infos">
            <h2><%= link_to booking.puppy.name, puppy_path(booking.puppy) %></h2>
            <p>You pet-a-puppy session is from the <%= booking.start_date %> to the <%= booking.end_date %></p>
              <% if booking.accepted == nil  %>
                  <p> Pending ... </p>
              <% elsif booking.accepted == false %>
                  <p>Sorry, your request got <strong>rejected</strong> by the owner. Find other <%= link_to 'cute puppies here' , puppies_path  %>.</p>
              <% else %>
                  <p>Yay, your pet-a-puppy session has been <strong>confirmed</strong> by the owner!</p>
              <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%# end %>

app/views/bookings/new.html.erb
<div class="container bg-white rounded text-warning pt-3 mt-3">
<h1 class="text-center">Book your pet-a-puppy session with <%= @puppy.name %></h1>
<div class="d-flex justify-content-center p-5">
<%= simple_form_for([ @puppy, @booking ]) do |f| %>
<div class="row form-inline text-secondary">
<%= f.input :start_date, as: :date, html5: true %>

<%= f.input :end_date, as: :date, html5: true %>

<%= f.submit class: "btn btn-warning text-white" %>
<% end %>
</div>
</div>
<%= link_to " ↪ Back to all puppies", root_path %>
</div>

app/views/bookings/show.html.erb
<div class="d-flex justify-content-center row ">
  <div class="col-sm-12 col-lg-6 " >
<div class="card-trip mt-3">
 <%= cl_image_tag @booking.puppy.photo.key,class: "card-img-top" %>
  <div class="card-trip-infos">
    <div>
      <h2> Thank you for your booking request for <%= @booking.puppy.name %></h2>
      <br>
      <p> We'll inform you when your session is confirmed by the dog owner.</p>

      <%= link_to "My dashboard", bookings_path, class: "btn btn-warning" %>
    </div>
    <h2 class="card-trip-pricing">€<%=@booking.puppy.price%>  </h2>

  </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetAPuppy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <!-- <div class="container"> -->
   <%= render 'shared/navbar' %>
   <%= render 'shared/flashes' %>
      <%= yield %>
   <%= render 'shared/footer' %>
    <!-- </div> -->
  </body>


</html>

app/views/pages/home.html.erb
<h1>Meet Puppies</h1>

app/views/puppies/index.html.erb
<div class="banner text-center"
style= "background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= image_path "puppies.jpg" %>');">
  <div class="container">
    <h1>Welcome to Pet-a-Puppy</h1>
    <p>Rent a puppy to have a relaxing time. At a location close to you</p>
    <div class="button-banner"><a class="btn btn-warning" href="#btn">Discover</a></div>
  </div>
</div>


<div id ="btn" class="container-map">
  <div class="cards ">
      <% @puppies.each do |puppy| %>

    <div class="card">
      <%= cl_image_tag puppy.photo.key, class: "card-img-top"%>
      <div class="card-body">
       <div class="d-flex justify-content-between align-items-center"> <h2><%= puppy.name %> </h2>
          <h5>€<%= puppy.price %> </h5>
          </div>
        <p class="card-text"><%= puppy.description%></p>
        <%= link_to "view details", puppy_path(puppy), class: "btn btn-warning" %>
      </div>
    </div>

      <% end %>
  </div>

<div id="map"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</div>


  <% if policy(Puppy).create? %>
    <%= link_to "New puppy", new_puppy_path %>
  <% end %>
</div>

app/views/puppies/new.html.erb
<div class="container">
<h1>Add a puppy to rent</h1>

<%= simple_form_for (@puppy) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :address %>
  <%= f.label "Add puppy photo" %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

</div>

app/views/puppies/show.html.erb
<div class="d-flex justify-content-center row ">
  <div class="col-sm-12 col-lg-6 " >
<div class="card-trip mt-3">
 <%= cl_image_tag @puppy.photo.key,class: "card-img-top" %>
  <div class="card-trip-infos">
    <div>
      <h2> <%= @puppy.name %> </h2>
      <br>
      <p> <%= @puppy.description %></p>
      <% if current_user != @puppy.user %>
      <%= link_to "Book a session now", new_puppy_booking_path(@puppy), class: "btn btn-warning" %>
      <% end %>
    </div>
    <h2 class="card-trip-pricing">€<%=@puppy.price%>  </h2>

     </div>
    </div>
  </div>
  </div>

<br>
<div class="d-flex justify-content-center"> <%= link_to "Back to all puppies", root_path, class: "btn btn-outline-warning" %></div>

app/views/shared/_flashes.html.erb
 <!-- Ensure you have flash messages in app/views/layouts/application.html.erb. for devise -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class= "footer" >

  <div class= "footer-links">
    <%= link_to do  %>
      <i class="fab fa-github"></i>
      <% end %>
    <%= link_to do  %>
      <i class="fab fa-instagram"></i>
      <% end %>
    <%= link_to do  %>
      <i class="fab fa-facebook"></i>
      <% end %>
    <%= link_to do  %>
      <i class="fab fa-twitter"></i>
      <% end %>
    <%= link_to do  %>
      <i class="fab fa-linkedin"></i>
    <% end %>


  </div>
    <div class= "footer-copyright">
    This footer is made with  <i class="fas fa-heart"></i> at Le Wagon
  </div>

</footer>

app/views/shared/_info_window.html.erb
<h2 class="text-warning"><%= link_to puppy.name, puppy_path(puppy) %></h2>
<p><%= cl_image_tag puppy.photo.key, class: "card-img-top"%></p>
<p><%= puppy.address %></p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %> <span class="puppy-title text-warning">Pet-a-Puppy</span>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to current_user.email.scan(/\w+/).first.capitalize, puppies_path , class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "My dashboard", bookings_path , class: "nav-link" %>
      </li>
      <% email_to_user = { 'amelie@example.com' => 'AmelieKerne', 'lena@example.com' => 'lenasophiea', 'mohit@example.com' => 'raoz87'} %>
      <li class="nav-item dropdown">
      <% if current_user.nil?  %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ClaireDMT", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{email_to_user[current_user.email]}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Login", user_session_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>